/* tslint:disable */
/* eslint-disable */
import { GraphQLResolveInfo, GraphQLScalarType } from 'graphql';
/**
 * This file is auto-generated by graphql-schema-typescript
 * Please note that any changes in this file may be overwritten
 */
 

/*******************************
 *                             *
 *          TYPE DEFS          *
 *                             *
 *******************************/
export interface gratiHubQuery {
  
  /**
   * grati.co graphQL API
   */
  viewer: gratiHubViewer;
  kernel: gratiHubKernel;
}

export interface gratiHubViewer {
  id: string;
  user?: gratiHubLoggedInUser;
  userSharedProjects: Array<gratiHubProject>;
  userGuid: string;
  getUserProjects: Array<gratiHubProject>;
  getUser?: gratiHubUser;
  getProject: gratiHubProject;
  userSubscription: gratiHubUserSubscription;
  userPublicKeys?: Array<gratiHubPublicKey | null>;
  getProjectCollaborators: Array<gratiHubUser>;
  getRepositories: Array<gratiHubRepository>;
}

export interface gratiHubLoggedInUser {
  id: number;
  login: string;
  full_name: string;
  avatar_url: string;
}

export interface gratiHubProject {
  id: number;
  username: string;
  full_name?: string;
  description?: string;
  location?: string;
  avatar_url?: string;
  website?: string;
}

export interface gratiHubUser {
  id: number;
  login: string;
  full_name?: string;
  avatar_url?: string;
  is_admin?: boolean;
}

export interface gratiHubUserSubscription {
  id: string;
  subscriptionId?: string;
  type?: string;
  userId?: number;
  userGuid?: string;
  activeSubscription?: boolean;
  hasProblems?: boolean;
}

export interface gratiHubPublicKey {
  id: number;
  name?: string;
}

export interface gratiHubRepository {
  id: number;
  name: string;
  full_name?: string;
  ssh_url: string;
  https_clone_url?: string;
  permissions?: gratiHubJSON;
  description?: string;
  private?: boolean;
  updated_at?: string;
  empty?: string;
  avatar_url?: string;
  mirror?: boolean;
  size: number;
  stars_count: number;
  watchers_count: number;
  website?: string;
  branches: Array<gratiHubRepositoryBranch>;
}

/**
 * The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf).
 */
export type gratiHubJSON = any;

export interface gratiHubRepositoryBranch {
  name: string;
  ref?: string;
  commit?: gratiHubRepositoryCommit;
}

export interface gratiHubRepositoryCommit {
  id: string;
  author?: gratiHubRepositoryCommitter;
  committer?: gratiHubRepositoryCommitter;
  message?: string;
  timestamp: string;
  verification?: gratiHubJSON;
}

export interface gratiHubRepositoryCommitter {
  name?: string;
  email?: string;
  username?: string;
}

export interface gratiHubKernel {
  id: string;
  getTheme?: gratiHubJSON;
  getProjectToken: string;
  userGuid: string;
  getProjectClaims: gratiHubProjectClaim;
  getProject: gratiHubProject;
  getProjectConfig: gratiHubJSON;
  getProjectRepositories: Array<gratiHubRepository>;
  getProjectBuildpack: Array<gratiHubRepository>;
  getWorkspace: gratiHubWorkspace;
  getProjectMirrors: Array<gratiHubRepositoryMirror>;
  getViewerOAuthProfile?: gratiHubJSON;
  getViewerOAuthIntallations: Array<gratiHubExternalInstallation | null>;
  getViewerOAuthIntallationRepositories: Array<gratiHubExternalRepository>;
  getProjectSubscription: gratiHubUserSubscription;
  getProjectWorkspaces: Array<gratiHubWorkspace>;
}

export interface gratiHubProjectClaim {
  userGuid: string;
  userId?: number;
  projectId: number;
}

export interface gratiHubWorkspace {
  id: string;
  name?: string;
  projectId: number;
  uid: string;
  isRealtime?: boolean;
}

export interface gratiHubRepositoryMirror {
  id: string;
  provider: string;
  installationId: string;
  repositoryId: string;
  sshURL: string;
}

export interface gratiHubExternalInstallation {
  id: number;
  provider: string;
  name: string;
}

export interface gratiHubExternalRepository {
  id: number;
  name: string;
  full_name: string;
}

export interface gratiHubMutation {
  logout: gratiHubViewer;
  loginUser?: gratiHubViewer;
  registerUser?: gratiHubViewer;
  createProject?: gratiHubProject;
  createRepository?: gratiHubKernel;
  deleteRepository?: gratiHubKernel;
  createRepositoryMirror?: gratiHubKernel;
  createPublicKey?: gratiHubPublicKey;
  deletePublicKey: boolean;
  updateProject?: gratiHubKernel;
  updateRepository?: gratiHubKernel;
  removeRepositoryMirror?: gratiHubKernel;
}

export enum gratiHubCacheControlScope {
  PUBLIC = 'PUBLIC',
  PRIVATE = 'PRIVATE'
}

export interface gratiHubProjectTeam {
  id: number;
  name?: string;
  members: Array<gratiHubUser>;
}

/**
 * The `Upload` scalar type represents a file upload.
 */
export type gratiHubUpload = any;

/*********************************
 *                               *
 *         TYPE RESOLVERS        *
 *                               *
 *********************************/
/**
 * This interface define the shape of your resolver
 * Note that this type is designed to be compatible with graphql-tools resolvers
 * However, you can still use other generated interfaces to make your resolver type-safed
 */
export interface gratiHubResolver {
  Query?: gratiHubQueryTypeResolver;
  Viewer?: gratiHubViewerTypeResolver;
  LoggedInUser?: gratiHubLoggedInUserTypeResolver;
  Project?: gratiHubProjectTypeResolver;
  User?: gratiHubUserTypeResolver;
  UserSubscription?: gratiHubUserSubscriptionTypeResolver;
  PublicKey?: gratiHubPublicKeyTypeResolver;
  Repository?: gratiHubRepositoryTypeResolver;
  JSON?: GraphQLScalarType;
  RepositoryBranch?: gratiHubRepositoryBranchTypeResolver;
  RepositoryCommit?: gratiHubRepositoryCommitTypeResolver;
  RepositoryCommitter?: gratiHubRepositoryCommitterTypeResolver;
  Kernel?: gratiHubKernelTypeResolver;
  ProjectClaim?: gratiHubProjectClaimTypeResolver;
  Workspace?: gratiHubWorkspaceTypeResolver;
  RepositoryMirror?: gratiHubRepositoryMirrorTypeResolver;
  ExternalInstallation?: gratiHubExternalInstallationTypeResolver;
  ExternalRepository?: gratiHubExternalRepositoryTypeResolver;
  Mutation?: gratiHubMutationTypeResolver;
  ProjectTeam?: gratiHubProjectTeamTypeResolver;
  Upload?: GraphQLScalarType;
}
export interface gratiHubQueryTypeResolver<TParent = any> {
  viewer?: QueryToViewerResolver<TParent>;
  kernel?: QueryToKernelResolver<TParent>;
}

export interface QueryToViewerResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface QueryToKernelResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubViewerTypeResolver<TParent = any> {
  id?: ViewerToIdResolver<TParent>;
  user?: ViewerToUserResolver<TParent>;
  userSharedProjects?: ViewerToUserSharedProjectsResolver<TParent>;
  userGuid?: ViewerToUserGuidResolver<TParent>;
  getUserProjects?: ViewerToGetUserProjectsResolver<TParent>;
  getUser?: ViewerToGetUserResolver<TParent>;
  getProject?: ViewerToGetProjectResolver<TParent>;
  userSubscription?: ViewerToUserSubscriptionResolver<TParent>;
  userPublicKeys?: ViewerToUserPublicKeysResolver<TParent>;
  getProjectCollaborators?: ViewerToGetProjectCollaboratorsResolver<TParent>;
  getRepositories?: ViewerToGetRepositoriesResolver<TParent>;
}

export interface ViewerToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToUserSharedProjectsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToUserGuidResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToGetUserProjectsArgs {
  username: string;
}
export interface ViewerToGetUserProjectsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: ViewerToGetUserProjectsArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToGetUserArgs {
  username?: string;
}
export interface ViewerToGetUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: ViewerToGetUserArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToGetProjectArgs {
  username: string;
}
export interface ViewerToGetProjectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: ViewerToGetProjectArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToUserSubscriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToUserPublicKeysResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToGetProjectCollaboratorsArgs {
  username: string;
}
export interface ViewerToGetProjectCollaboratorsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: ViewerToGetProjectCollaboratorsArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ViewerToGetRepositoriesArgs {
  username?: string;
}
export interface ViewerToGetRepositoriesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: ViewerToGetRepositoriesArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubLoggedInUserTypeResolver<TParent = any> {
  id?: LoggedInUserToIdResolver<TParent>;
  login?: LoggedInUserToLoginResolver<TParent>;
  full_name?: LoggedInUserToFull_nameResolver<TParent>;
  avatar_url?: LoggedInUserToAvatar_urlResolver<TParent>;
}

export interface LoggedInUserToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface LoggedInUserToLoginResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface LoggedInUserToFull_nameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface LoggedInUserToAvatar_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubProjectTypeResolver<TParent = any> {
  id?: ProjectToIdResolver<TParent>;
  username?: ProjectToUsernameResolver<TParent>;
  full_name?: ProjectToFull_nameResolver<TParent>;
  description?: ProjectToDescriptionResolver<TParent>;
  location?: ProjectToLocationResolver<TParent>;
  avatar_url?: ProjectToAvatar_urlResolver<TParent>;
  website?: ProjectToWebsiteResolver<TParent>;
}

export interface ProjectToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToUsernameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToFull_nameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToDescriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToLocationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToAvatar_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectToWebsiteResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubUserTypeResolver<TParent = any> {
  id?: UserToIdResolver<TParent>;
  login?: UserToLoginResolver<TParent>;
  full_name?: UserToFull_nameResolver<TParent>;
  avatar_url?: UserToAvatar_urlResolver<TParent>;
  is_admin?: UserToIs_adminResolver<TParent>;
}

export interface UserToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToLoginResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToFull_nameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToAvatar_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserToIs_adminResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubUserSubscriptionTypeResolver<TParent = any> {
  id?: UserSubscriptionToIdResolver<TParent>;
  subscriptionId?: UserSubscriptionToSubscriptionIdResolver<TParent>;
  type?: UserSubscriptionToTypeResolver<TParent>;
  userId?: UserSubscriptionToUserIdResolver<TParent>;
  userGuid?: UserSubscriptionToUserGuidResolver<TParent>;
  activeSubscription?: UserSubscriptionToActiveSubscriptionResolver<TParent>;
  hasProblems?: UserSubscriptionToHasProblemsResolver<TParent>;
}

export interface UserSubscriptionToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToSubscriptionIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToTypeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToUserIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToUserGuidResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToActiveSubscriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface UserSubscriptionToHasProblemsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubPublicKeyTypeResolver<TParent = any> {
  id?: PublicKeyToIdResolver<TParent>;
  name?: PublicKeyToNameResolver<TParent>;
}

export interface PublicKeyToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface PublicKeyToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubRepositoryTypeResolver<TParent = any> {
  id?: RepositoryToIdResolver<TParent>;
  name?: RepositoryToNameResolver<TParent>;
  full_name?: RepositoryToFull_nameResolver<TParent>;
  ssh_url?: RepositoryToSsh_urlResolver<TParent>;
  https_clone_url?: RepositoryToHttps_clone_urlResolver<TParent>;
  permissions?: RepositoryToPermissionsResolver<TParent>;
  description?: RepositoryToDescriptionResolver<TParent>;
  private?: RepositoryToPrivateResolver<TParent>;
  updated_at?: RepositoryToUpdated_atResolver<TParent>;
  empty?: RepositoryToEmptyResolver<TParent>;
  avatar_url?: RepositoryToAvatar_urlResolver<TParent>;
  mirror?: RepositoryToMirrorResolver<TParent>;
  size?: RepositoryToSizeResolver<TParent>;
  stars_count?: RepositoryToStars_countResolver<TParent>;
  watchers_count?: RepositoryToWatchers_countResolver<TParent>;
  website?: RepositoryToWebsiteResolver<TParent>;
  branches?: RepositoryToBranchesResolver<TParent>;
}

export interface RepositoryToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToFull_nameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToSsh_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToHttps_clone_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToPermissionsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToDescriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToPrivateResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToUpdated_atResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToEmptyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToAvatar_urlResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToMirrorResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToSizeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToStars_countResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToWatchers_countResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToWebsiteResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryToBranchesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubRepositoryBranchTypeResolver<TParent = any> {
  name?: RepositoryBranchToNameResolver<TParent>;
  ref?: RepositoryBranchToRefResolver<TParent>;
  commit?: RepositoryBranchToCommitResolver<TParent>;
}

export interface RepositoryBranchToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryBranchToRefResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryBranchToCommitResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubRepositoryCommitTypeResolver<TParent = any> {
  id?: RepositoryCommitToIdResolver<TParent>;
  author?: RepositoryCommitToAuthorResolver<TParent>;
  committer?: RepositoryCommitToCommitterResolver<TParent>;
  message?: RepositoryCommitToMessageResolver<TParent>;
  timestamp?: RepositoryCommitToTimestampResolver<TParent>;
  verification?: RepositoryCommitToVerificationResolver<TParent>;
}

export interface RepositoryCommitToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitToAuthorResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitToCommitterResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitToMessageResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitToTimestampResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitToVerificationResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubRepositoryCommitterTypeResolver<TParent = any> {
  name?: RepositoryCommitterToNameResolver<TParent>;
  email?: RepositoryCommitterToEmailResolver<TParent>;
  username?: RepositoryCommitterToUsernameResolver<TParent>;
}

export interface RepositoryCommitterToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitterToEmailResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryCommitterToUsernameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubKernelTypeResolver<TParent = any> {
  id?: KernelToIdResolver<TParent>;
  getTheme?: KernelToGetThemeResolver<TParent>;
  getProjectToken?: KernelToGetProjectTokenResolver<TParent>;
  userGuid?: KernelToUserGuidResolver<TParent>;
  getProjectClaims?: KernelToGetProjectClaimsResolver<TParent>;
  getProject?: KernelToGetProjectResolver<TParent>;
  getProjectConfig?: KernelToGetProjectConfigResolver<TParent>;
  getProjectRepositories?: KernelToGetProjectRepositoriesResolver<TParent>;
  getProjectBuildpack?: KernelToGetProjectBuildpackResolver<TParent>;
  getWorkspace?: KernelToGetWorkspaceResolver<TParent>;
  getProjectMirrors?: KernelToGetProjectMirrorsResolver<TParent>;
  getViewerOAuthProfile?: KernelToGetViewerOAuthProfileResolver<TParent>;
  getViewerOAuthIntallations?: KernelToGetViewerOAuthIntallationsResolver<TParent>;
  getViewerOAuthIntallationRepositories?: KernelToGetViewerOAuthIntallationRepositoriesResolver<TParent>;
  getProjectSubscription?: KernelToGetProjectSubscriptionResolver<TParent>;
  getProjectWorkspaces?: KernelToGetProjectWorkspacesResolver<TParent>;
}

export interface KernelToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetThemeArgs {
  name: string;
}
export interface KernelToGetThemeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetThemeArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectTokenArgs {
  projectName: string;
  workspaceId?: string;
}
export interface KernelToGetProjectTokenResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectTokenArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToUserGuidResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectClaimsArgs {
  projectToken: string;
}
export interface KernelToGetProjectClaimsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectClaimsArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectArgs {
  projectToken: string;
}
export interface KernelToGetProjectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectConfigArgs {
  projectToken: string;
}
export interface KernelToGetProjectConfigResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectConfigArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectRepositoriesArgs {
  projectToken: string;
  projectName: string;
}
export interface KernelToGetProjectRepositoriesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectRepositoriesArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectBuildpackArgs {
  projectToken: string;
}
export interface KernelToGetProjectBuildpackResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectBuildpackArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetWorkspaceArgs {
  projectToken: string;
  workspaceId: string;
}
export interface KernelToGetWorkspaceResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetWorkspaceArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectMirrorsArgs {
  projectToken: string;
}
export interface KernelToGetProjectMirrorsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectMirrorsArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetViewerOAuthProfileArgs {
  projectToken: string;
}
export interface KernelToGetViewerOAuthProfileResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetViewerOAuthProfileArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetViewerOAuthIntallationsArgs {
  projectToken: string;
}
export interface KernelToGetViewerOAuthIntallationsResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetViewerOAuthIntallationsArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetViewerOAuthIntallationRepositoriesArgs {
  projectToken: string;
  installationId: number;
}
export interface KernelToGetViewerOAuthIntallationRepositoriesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetViewerOAuthIntallationRepositoriesArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectSubscriptionArgs {
  projectToken: string;
}
export interface KernelToGetProjectSubscriptionResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectSubscriptionArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface KernelToGetProjectWorkspacesArgs {
  projectToken: string;
}
export interface KernelToGetProjectWorkspacesResolver<TParent = any, TResult = any> {
  (parent: TParent, args: KernelToGetProjectWorkspacesArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubProjectClaimTypeResolver<TParent = any> {
  userGuid?: ProjectClaimToUserGuidResolver<TParent>;
  userId?: ProjectClaimToUserIdResolver<TParent>;
  projectId?: ProjectClaimToProjectIdResolver<TParent>;
}

export interface ProjectClaimToUserGuidResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectClaimToUserIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectClaimToProjectIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubWorkspaceTypeResolver<TParent = any> {
  id?: WorkspaceToIdResolver<TParent>;
  name?: WorkspaceToNameResolver<TParent>;
  projectId?: WorkspaceToProjectIdResolver<TParent>;
  uid?: WorkspaceToUidResolver<TParent>;
  isRealtime?: WorkspaceToIsRealtimeResolver<TParent>;
}

export interface WorkspaceToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WorkspaceToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WorkspaceToProjectIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WorkspaceToUidResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface WorkspaceToIsRealtimeResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubRepositoryMirrorTypeResolver<TParent = any> {
  id?: RepositoryMirrorToIdResolver<TParent>;
  provider?: RepositoryMirrorToProviderResolver<TParent>;
  installationId?: RepositoryMirrorToInstallationIdResolver<TParent>;
  repositoryId?: RepositoryMirrorToRepositoryIdResolver<TParent>;
  sshURL?: RepositoryMirrorToSshURLResolver<TParent>;
}

export interface RepositoryMirrorToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryMirrorToProviderResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryMirrorToInstallationIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryMirrorToRepositoryIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface RepositoryMirrorToSshURLResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubExternalInstallationTypeResolver<TParent = any> {
  id?: ExternalInstallationToIdResolver<TParent>;
  provider?: ExternalInstallationToProviderResolver<TParent>;
  name?: ExternalInstallationToNameResolver<TParent>;
}

export interface ExternalInstallationToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ExternalInstallationToProviderResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ExternalInstallationToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubExternalRepositoryTypeResolver<TParent = any> {
  id?: ExternalRepositoryToIdResolver<TParent>;
  name?: ExternalRepositoryToNameResolver<TParent>;
  full_name?: ExternalRepositoryToFull_nameResolver<TParent>;
}

export interface ExternalRepositoryToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ExternalRepositoryToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ExternalRepositoryToFull_nameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubMutationTypeResolver<TParent = any> {
  logout?: MutationToLogoutResolver<TParent>;
  loginUser?: MutationToLoginUserResolver<TParent>;
  registerUser?: MutationToRegisterUserResolver<TParent>;
  createProject?: MutationToCreateProjectResolver<TParent>;
  createRepository?: MutationToCreateRepositoryResolver<TParent>;
  deleteRepository?: MutationToDeleteRepositoryResolver<TParent>;
  createRepositoryMirror?: MutationToCreateRepositoryMirrorResolver<TParent>;
  createPublicKey?: MutationToCreatePublicKeyResolver<TParent>;
  deletePublicKey?: MutationToDeletePublicKeyResolver<TParent>;
  updateProject?: MutationToUpdateProjectResolver<TParent>;
  updateRepository?: MutationToUpdateRepositoryResolver<TParent>;
  removeRepositoryMirror?: MutationToRemoveRepositoryMirrorResolver<TParent>;
}

export interface MutationToLogoutResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToLoginUserArgs {
  email: string;
  password: string;
}
export interface MutationToLoginUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToLoginUserArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToRegisterUserArgs {
  email: string;
  password: string;
  name: string;
  username?: string;
}
export interface MutationToRegisterUserResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToRegisterUserArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToCreateProjectArgs {
  name: string;
  buildpack: string;
}
export interface MutationToCreateProjectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreateProjectArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToCreateRepositoryArgs {
  projectToken: string;
  name: string;
  isPublic: boolean;
}
export interface MutationToCreateRepositoryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreateRepositoryArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToDeleteRepositoryArgs {
  projectToken: string;
  repoId: number;
}
export interface MutationToDeleteRepositoryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToDeleteRepositoryArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToCreateRepositoryMirrorArgs {
  projectToken: string;
  repoId: number;
  providerName: string;
  providerRepoId: number;
  mirrorOwner: string;
  mirrorRepo: string;
}
export interface MutationToCreateRepositoryMirrorResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreateRepositoryMirrorArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToCreatePublicKeyArgs {
  name: string;
  value: string;
}
export interface MutationToCreatePublicKeyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToCreatePublicKeyArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToDeletePublicKeyArgs {
  id: number;
}
export interface MutationToDeletePublicKeyResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToDeletePublicKeyArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToUpdateProjectArgs {
  projectToken: string;
  config: string;
}
export interface MutationToUpdateProjectResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToUpdateProjectArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToUpdateRepositoryArgs {
  projectToken: string;
  repoId: number;
  isPublic: boolean;
}
export interface MutationToUpdateRepositoryResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToUpdateRepositoryArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface MutationToRemoveRepositoryMirrorArgs {
  projectToken: string;
  mirrorId: string;
}
export interface MutationToRemoveRepositoryMirrorResolver<TParent = any, TResult = any> {
  (parent: TParent, args: MutationToRemoveRepositoryMirrorArgs, context: any, info: GraphQLResolveInfo): TResult;
}

export interface gratiHubProjectTeamTypeResolver<TParent = any> {
  id?: ProjectTeamToIdResolver<TParent>;
  name?: ProjectTeamToNameResolver<TParent>;
  members?: ProjectTeamToMembersResolver<TParent>;
}

export interface ProjectTeamToIdResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectTeamToNameResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}

export interface ProjectTeamToMembersResolver<TParent = any, TResult = any> {
  (parent: TParent, args: {}, context: any, info: GraphQLResolveInfo): TResult;
}
